In [26]:
from numpy import empty

# Test n°2 d'algo



NB : les exercices peuvent être traites indépendamment, *y compris* lorsqu'on vous demande d'utiliser une fonction d'un exercice précédent. En effet, vous n'avez besoin que du contrat (qui vous est donné) pour pouvoir utiliser une fonction.

Rappel : pour créer un tableau d'entiers non initialisé de taille N, on utilise ``empty(N, int)``.

## Exercice 1 : comptage (/2)

Écrivez l'algorithme ci-dessous, qui compte le nombre d'occurrences d'un caractère ``car`` dans une chaîne ``txt``.

In [27]:
def compte_caractère(txt, car):
    """
    :entrée txt: str
    :entrée car: str
    :pré-cond: len(car) = 1
    :sortie nbc: int
    :post-cond: nbc est le nombre d'occurences de `car` dans `txt`
    """
    nbc = 0
    i = 0
    while i < len(txt):
        if txt[i] == car:
            nbc = nbc+1
        i = i+1
    return nbc

# version récursive

def compte_caractère(txt, car):
    if len(txt) == 0:
        nbc = 0
    else:
        nbc = 0
        if txt[0] == car:
            nbc = nbc+1
        nbc = nbc + compte_caractère(txt[1:], car)
    return nbc

# TESTONS
print( compte_caractère("hello", "l") )
print( compte_caractère("un deux trois quatre", " ") )

2
3


## Exercice 2 : repérons les mots (/4)

On considère des chaînes de caractères représentant des phrases simples :
* elle ne contient que des lettres et des espaces,
* elle se commence et se termine par une lettre,
* les mots sont séparés par exactement une espace.

NB : par "mot", on entend ici n'importe quelle suite de lettres, pas forcément un mot du dictionnaire. Donc les conditions ci-dessus sont satisfaites par la chaînes ``"Mignonne allons voir si la rose"``, mais aussi par ``"sqJlIQx zlkD iOsQx"``.

On souhaite, écrire une fonction qui nous retourne un tableau contenant l'indice de début de chaque mot. Par exemple, ``indices_mots("Mignonne allons voir si la rose")`` retournera un tableau de longueur 6 (puisqu'il y a six mots) contenant les valeurs 0, 9, 16, 21, 24 et 27.


In [28]:
def indices_mots(phrase):
    """
    :entrée phrase: str
    :pré-cond: phrase est une phrase simple comme définie dans l'énnoncé
    :sortie indices: tableau d'entiers
    :post-cond: `indices` a pour longueur le nombre de mots de `phrase`;
                `indices` contient, dans l'ordre, les indices de début de chaque mot de `phrase`.
    """
    nbmots = compte_caractère(phrase, " ")+1
    indices = empty(nbmots, int)

    indices[0] = 0
    i = 1 # indice sur phrase
    j = 1 # indice sur indices
    while j < nbmots:
        if phrase[i] == " ":
            indices[j] = i+1
            j = j+1
        i = i+1
    return indices
 
# TESTONS
vers = "Mignonne allons voir si la rose"
print(indices_mots(vers))
i
for i in indices_mots(vers):
    print(vers[i:])


[ 0  9 16 21 24 27]
Mignonne allons voir si la rose
allons voir si la rose
voir si la rose
si la rose
la rose
rose


NB: on remarque que, pour connaître le nombre de mots, il est utile de connaître le nombre d'espaces dans la chaîne, et que pour cela on peut utiliser la fonction ``compte_caractère`` définie ci-dessus.

## Exercice 3 : un peu de lecture (/4)

Considérez l'algorithme ci-dessous.

1. Exécutez la trace de cet algorithme pour la chaîne ``" C'est  simple! "`` (avec une espace au début, deux espaces au milieu et une espace à la fin).
2. Écrivez le contrat de cet algorithme, en donnant notamment sa post-condition : que calcule-t-il ?
3. Expliquez le rôle de la variable intermédiaire ``w`` dans l'exécution de cet algorithme.

In [50]:
def mystère(txt):
    s = 0
    w = False
    i = 0
    print("===  i     w  s  txt[i]")
    print("=== %2s %5s %2s  %s" % (i, w, s, txt[i]))
    while i < len(txt):
        if compte_caractère(" .,;:'!", txt[i]) == 0:
            if not w:
                s = s+1
            w = True
        else:
            w = False
        i = i+1
        print("=== %2s %5s %2s  %s" % (i, w, s, (i<len(txt) and txt[i] or "X")))
    return s

# TESTONS
mystère(" C'est simple! ")

===  i     w  s  txt[i]
===  0 False  0   
===  1 False  0  C
===  2  True  1  '
===  3 False  1  e
===  4  True  2  s
===  5  True  2  t
===  6  True  2   
===  7 False  2  s
===  8  True  3  i
===  9  True  3  m
=== 10  True  3  p
=== 11  True  3  l
=== 12  True  3  e
=== 13  True  3  !
=== 14 False  3   
=== 15 False  3  X


3

## Exercice 4: le triangle de Pascal, petit à petit (/3)

Le triangle de Pascal (illustré ci-dessous) est une figure composée de nombres entiers. Plus précisément :

* Le premier étage (en partant du haut) contient un seul nombre.
* Chaque étage suivant comporte un nombre de plus que le précédent.
* Tous les étages commencent par 1 et se terminent par 1.
* Toute valeur intermédiaire est calculée en additionnant deux valeurs de l'étage du dessus : la valeur située juste au dessus d'elle, et celle située immédiatement à gauche.

```
1
1  1
1  2  1
1  3  3  1
1  4  6  4  1
1  5 10 10  5  1
etc...
```

On vous demande ici d'écrire une fonction qui, étant donnée un étage du triangle de Pascal (représenté par un tableau d'entiers), produit un nouveau tableau correspondant à l'étage suivant.

Par exemple, ``étage_suivant([1,3,3,1])`` doit retourner ``[1,4,6,4,1]``.

In [30]:
def étage_suivant(étage):
    """
    :entrée étage: tableau d'entiers
    :pré-cond: `étage` représente un étage quelconque du triangle de Pascal
    :sortie suivant: tableau d'entiers
    :post-cond: `suivant` représente l'étage suitué en dessous de `étage` dans le triange de Pascal
    """
    suivant = empty(len(étage)+1, int)
    suivant[0] = 1
    suivant[len(suivant)-1] = 1
    
    i = 1
    while i < len(étage):
        suivant[i] = étage[i] + étage[i-1]
        i = i+1
        
    return suivant

# TESTONS
et = [1]
while len(et) < 7:
    et = étage_suivant(et)
    print(et)

[1 1]
[1 2 1]
[1 3 3 1]
[1 4 6 4 1]
[ 1  5 10 10  5  1]
[ 1  6 15 20 15  6  1]


## Exercice 5 : le triangle de Pascal par ascenseur (/3)

On vous demande maintenant d'écrire de manière **récursive** la fonction suivante,
qui calcule le n-ème étage du triangle de Pascal (décrit dans l'exercice précédent).
Notez bien que, cette fois, la seule valeur d'entrée de l'algorithme est l'entier *n*.
Par exemple, ``étage_pascal(5)`` doit retourner ``[1,4,6,4,1]``.

Il vous sera nécessaire d'utiliser la fonction ``étage_suivant`` décrite dans l'exercice précédent.

In [51]:
def étage_pascal(n):
    """
    :entrée n: int
    :pré-cond: n ≥ 1
    :sortie étage: tableau d'entiers
    :post-cond: `étage` représente le n-ème étage du triangle de Pascal
    """
    if n == 1:
        étage = empty(1, int)
        étage[0] = 1
    else:
        précédent = étage_pascal(n-1)
        étage = étage_suivant(précédent)
        
    return étage

# TESTONS
i = 1
while i < 8:
    print(étage_pascal(i))
    i = i+1

[1]
[1 1]
[1 2 1]
[1 3 3 1]
[1 4 6 4 1]
[ 1  5 10 10  5  1]
[ 1  6 15 20 15  6  1]


## Exercice 6 : Pascal fait du sur-place (/3)

On souhaite à nouveau calculer un étage du triangle de Pascal à partir de l'étage précédent,
mais cette fois ci, au lieu de produire un nouveau tableau,
on souhaite remplacer les valeurs du tableau passé en paramètre.

NB : Pour que cela soit possible,
il faut que le tableau passé en paramètre ait une longueur suffisante pour contenir l'étage suivant,
ce que garantissent les pré-conditions du contrat ci-dessous.

In [52]:
def étage_suivant_en_place(étage, n):
    """
    :entrée/sortie étage: tableau d'entiers
    :entrée n: int
    :pré-cond: len(étage) ≥ n+1 ;
               étageₑ contient l'étage n du triangle de Pascal
    :post-cond: étageₛ contient l'étage n+1 du triangle de Pascal
    """
    étage[n] = 1 # dernière case
    i = n-1 # avant-dernière case
    while i > 0:
        étage[i] = étage[i] + étage[i-1]
        i = i-1

# TESTONS
étage = [1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
i = 0
while i < 8:
    print(étage[:i])
    étage_suivant_en_place(étage, i)
    i = i+1

[]
[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]
[1, 6, 15, 20, 15, 6, 1]
